### ISSUE TITLE
[BUG] - Cannot Remove colorRoles

### ISSUE THREAD

**Issue by yourantithesis** [nhcarrigan/discordBoostMonitor#194]
### What bug did you encounter?

Bot didn't remove colorRoles after boost roles removed

### What did you expect to happen?

The ColorRoles Should Be Removed After The Boost Roles Removed

### Screenshots

![Screenshot_88](https://user-images.githubusercontent.com/111164892/194690307-021817b3-f152-45cb-9c2f-b40415391c2b.png)
After Boost Roles Removed
``
![Screenshot_89](https://user-images.githubusercontent.com/111164892/194690353-cc8fecef-8c69-4a41-8743-e7c677b52d80.png)
Nothing Happend :( The Color Roles Not Deleted

and here's the log
![Screenshot_90](https://user-images.githubusercontent.com/111164892/194690774-e57b70b3-2e10-48f4-9ec0-bf6c59efe7cd.png)

**Comment by naomi-lgbt** [comment]
Make sure the bot has a role higher than all of the booster roles.

**Comment by yourantithesis** [comment]
> Make sure the bot has a role higher than all of the booster roles.

the bot is already have the higher role ( utility bot ), than others booster roles :(
![Screenshot_91](https://user-images.githubusercontent.com/111164892/194697091-30ef9d9a-0a63-45b2-88d9-6eb5dd4609cb.png)

**Comment by naomi-lgbt** [comment]
Hey there, looks like you closed this issue - were you able to resolve the problem?
